server:
  port: 8435
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /cxtk
spring:
  datasource:
    url: jdbc:mysql://47.112.15.249:3306/chaoxingtopic?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password: 981623
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
mybatis:
  type-aliases-package: site.ccczg.chaoxingtopic.bean
logging:
  level:
    root: info
    site.ccczg.chaoxingtopic: debug
    file: log/chaoxinglog.log