server:
  port: 8435
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /cxtk

spring:
  datasource:
    url: jdbc:mysql://xxxxxx:3306/chaoxingtopic?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: xxxxx
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
mybatis:
  type-aliases-package: site.ccczg.chaoxingtopic.bean